### PR TITLE
Use setting 'enable_tool_wear' to enable/disable tools wearing/breaking

### PR DESCRIPTION
**Pull request by AntumDeluge**
- Default: true
- If 'false', tools will not wear or break when used for digging,
chopping, etc.

### CODE REVIEW

**Comment by AntumDeluge** [comment]
Just a note on this: I created a mod that allows tool/weapon/armor wear to be disabled for any mod's items: [equip_wear](https://content.minetest.net/packages/AntumDeluge/equip_wear/)

**Comment by FsxShader2012** [comment]
Hey Antum,

thanks for the info. If you would like to resubmit the request I'd gladly merge it to the master branch. I think this is a nice addition. Back when I developed this mod, Minetest didn't support mod options I believe although I could be wrong.

**Comment by AntumDeluge** [comment]
Honestly, I think it is best to leave it as it is. Most other mod developers don't seem to want to add the option. So if anyone wants to disable wear, they should just include a mod like `equip_wear` to do it.

**Comment by FsxShader2012** [comment]
Alright, no worries. Thanks for the suggestion though!

**Pull request closed without merging**
